language: scala
sudo: false
script: sbt -jvm-opts jvmopts.travis test
jdk:
- oraclejdk8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7053daf92ef3da0554f0
    on_success: change
    on_failure: always
    on_start: false
after_success:
- ! '[[ $TRAVIS_BRANCH == "develop" ]] && { sbt "publish" ; };'
env:
  global:
  - secure: KmlVT4hJtAY8nqI/pT+XrcfizFS1PEBMuHOycVUXpDU2F4Nk9nffOe59KplnryH3QtRdFjXmrhWC+5rcmkSU89ZW4SUHhLiwDP2czXOwEZMwXdDu7AwQzng5CbGAEszhtZxHy/eW350sGqmM93KuQJD9Yd2qS4p3yhefuQgKSyCbAPyQBMoZ7dGIeWxKbdHqOKLo3xFuU1grvSD/yEzXVWgCFY1srfGArruJx8eumJ+Wui/qJ0G/9ckwOK1F1spoKEaPJSxF+OcLpE0PUiAgiMmhqtKhyJlYKGqaoXxb2g8SjP0ZOnHqjlWAZ0JaE1ktTbKzJRwAHi7OuGKxRg28TvSLL8KGPA6Mo+q/wjS3nnC3swp03PacTM8zHaDkphlOvh0J0xO2AJQTVG5uQkCyGAp8mOG2oaTSMJBS5zKBzYIsBl5zhsyXINmaWVXblv1h8ALJCVRv6n0iawJCRZrniySjnIq5b1hoxwXkGitzC+XxqBubVO/P2L6UF91/0XiNuO3BVAbwnr46u49r9M0qMnswbsHcfxOdqCu7ojTw0m7OZFo9eYofXvXhm574grqFASdidB43MUCYzm15k+XJyHDzonf+O+/zdmrNjGMyDQ50YKuQjUpTy1mOMTGO+WN3e6eT/IsCT8Udcqw5BP5naaERAuuqh5g0afLJ1JOTBNw=
  - secure: YDHvhmjnVxhxLcpDhw5PtICvJTz5l5ItIkaRvFRf2x4SRDWgdRz2drwlyFg0WmOaKgEPnQ8RMwQEXY3HQdH1eQ4WayegzMyAbK5/iUcYhWuickCY1KSHuOjgQjzT18ldCca0aQDL3weEDTKNfC4ovkW4+eVBI5L2mFC1CHtk7R6P0MHLfRmUYkAIZHpgASOvs0E68XDhJ6A0iRz8AQQPB1dbVh3lAdMRdljaCBqPGd6QawOs3iba929cNGq9o9swVoJJSiHXCp2D1QajBs5lM5e/StYjVcnZAbWQQwcrwFQFEwjvMRzQJNapPOI3lxEgzg7mZSsZu02wWnIa/ZRkEijvHCDslaXkjuYrNWapaYp82PX3Lm48JcWjXTN0XVLP8mJIxs9bgJRtV8bxchtoQVGv49fkK2NKo1OFYW0KVYTiwAVT1CMmE931PuyEfVhO2VXe/GlYJvW/L/AQSrUMEytLrOTgOue0xcXn14JuxzOtZyh4EK9Vpn+yD5FDDdqqD9pE6czuLk01bWoemkgtcoBs2WUbStGTadRLA1U+ClL97JHVyMfN5LCmkoj40DE5THHLZ3+ozyz29pH/zsCFKwDigehPSlM8NO6zrzRdCWQd4XmZ5kTsy8Um39ItJRq8rJGk1Y65p+lbPS68sr5Td5gpAe861l8hsotaATpt+LI=
